name: Redis Health Check

on:
  schedule:
    # Run every 5 days at midnight UTC
    - cron: '0 0 */5 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping-redis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Redis Service
      run: |
        echo "Pinging Redis service..."
        
        # Ping the Redis endpoint (replace with your actual domain when deployed)
        response=$(curl -s -w "%{http_code}" \
          -H "Authorization: Bearer ${{ secrets.PING_SECRET }}" \
          -H "Content-Type: application/json" \
          "${{ secrets.APP_URL }}/api/ping-redis")
        
        http_code="${response: -3}"
        body="${response%???}"
        
        echo "HTTP Status: $http_code"
        echo "Response Body: $body"
        
        if [ "$http_code" -eq 200 ]; then
          echo "✅ Redis ping successful!"
        else
          echo "❌ Redis ping failed with status $http_code"
          echo "Response: $body"
          exit 1
        fi
        
    - name: Log timestamp
      run: |
        echo "Redis health check completed at: $(date)"
        echo "Next check scheduled in 5 days"
